# Generated by Django 4.1.4 on 2022-12-31 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMDBModel",
            fields=[
                (
                    "updated_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True,
                        default=datetime.datetime(2022, 12, 31, 15, 50, 41, 234654),
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("main_poster", models.URLField(blank=True, null=True)),
                (
                    "imdb_id",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("rate", models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="GalleryModel",
            fields=[
                (
                    "updated_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True,
                        default=datetime.datetime(2022, 12, 31, 15, 50, 41, 234654),
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "imdb_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imdb_vod.imdbmodel",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
