# Generated by Django 4.1.4 on 2022-12-31 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("imdb_vod", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerymodel",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2022, 12, 31, 16, 17, 55, 482070),
            ),
        ),
        migrations.AlterField(
            model_name="gallerymodel",
            name="imdb_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imdb_content_gallery",
                related_query_name="imdb_gallery",
                to="imdb_vod.imdbmodel",
            ),
        ),
        migrations.AlterField(
            model_name="imdbmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2022, 12, 31, 16, 17, 55, 482070),
            ),
        ),
    ]
