# Generated by Django 4.1.4 on 2022-12-31 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("imdb_vod", "0002_alter_gallerymodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerymodel",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2022, 12, 31, 16, 37, 28, 165331),
            ),
        ),
        migrations.AlterField(
            model_name="imdbmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(2022, 12, 31, 16, 37, 28, 165331),
            ),
        ),
        migrations.CreateModel(
            name="RelatedContentModel",
            fields=[
                (
                    "updated_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_created=True,
                        default=datetime.datetime(2022, 12, 31, 16, 37, 28, 165331),
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "imdb_origin_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_origin_related",
                        related_query_name="content_origin_related",
                        to="imdb_vod.imdbmodel",
                    ),
                ),
                (
                    "imdb_related_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_related",
                        related_query_name="content_related",
                        to="imdb_vod.imdbmodel",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
